services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    volumes:
      - ./homeassistant/config:/config
    environment:
      - TZ=America/New_York
    ports:
      - "8123:8123"
    restart: unless-stopped

  # mosquitto:
  #   container_name: mosquitto
  #   image: eclipse-mosquitto:latest
  #   volumes:
  #     - ./mosquitto/config:/mosquitto/config
  #     - ./mosquitto/data:/mosquitto/data
  #   ports:
  #     - "1883:1883"
  #     - "9001:9001"
  #   restart: unless-stopped
