esphome:
  name: kitchen

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  port: 6053

wifi:
  ssid: "showthesign"
  password: "f334p8ofpehgb"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bryans_Hotspot"
    password: "R0OF7ZllNiAf"
    # showthesign
    # f334p8ofpehgb

captive_portal:

switch:
  - platform: gpio
    name: "Kitchen Light 1"
    pin: 5
